DROP TABLE IF EXISTS state;
DROP TABLE IF EXISTS outcomes;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS analytics;
DROP TABLE IF EXISTS actions;
DROP TABLE IF EXISTS triggers;
DROP TABLE IF EXISTS users;


