version: 2.1

image_name: &image_name 'halxyz/zoroaster'

orbs:
  docker: circleci/docker@1.2.1
  aws-ecs: circleci/aws-ecs@1.2.0

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: *image_name
          tag: $CIRCLE_BRANCH
      - docker/push:
          digest-path: /tmp/digest.txt
          image: *image_name
          tag: $CIRCLE_BRANCH
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"


workflows:
  build-docker-image-only:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - staging
                - master
      - aws-ecs/deploy-service-update:
          family: "zoroaster-service"
          cluster-name: "halxyz-staging-cluster"
          container-image-name-updates: "container=zoroaster-service,tag=${CIRCLE_BRANCH}"
          container-env-var-updates: "
          container=zoroaster-service,name=STAGE,value=STAGING,
          container=zoroaster-service,name=DB_HOST,value=${DB_HOST},
          container=zoroaster-service,name=DB_NAME,value=${DB_NAME},
          container=zoroaster-service,name=DB_USR,value=${DB_USR},
          container=zoroaster-service,name=DB_PWD,value=${DB_PWD},
          container=zoroaster-service,name=ETH_NODE,value=${ETH_NODE_STAGING},
          container=zoroaster-service,name=BACKUP_NODE,value=${ETH_NODE_STAGING},
          container=zoroaster-service,name=RINKEBY_NODE,value=${RINKEBY_NODE},
          container=zoroaster-service,name=TWITTER_CONSUMER_KEY,value=${TWITTER_CONSUMER_KEY},
          container=zoroaster-service,name=TWITTER_CONSUMER_SECRET,value=${TWITTER_CONSUMER_SECRET},
          container=zoroaster-service,name=NETWORK,value=1_eth_mainnet,
          container=zoroaster-service,name=BLOCKS_DELAY,value=${BLOCKS_DELAY_ETH_MAINNET},
          container=zoroaster-service,name=POLLING_INTERVAL,value=${POLLING_INTERVAL_ETH_MAINNET},
          container=zoroaster-service,name=BLOCKS_INTERVAL,value=${BLOCKS_INTERVAL_ETH_MAINNET},
          container=zoroaster-service,name=ETHERSCAN_KEY,value=${ETHERSCAN_KEY}"
          filters:
            branches:
              only: staging
          requires:
            - build-and-push
      - aws-ecs/deploy-service-update:
          family: "zoroaster-service-xdai"
          cluster-name: "halxyz-staging-cluster"
          container-image-name-updates: "container=zoroaster-service-xdai,tag=${CIRCLE_BRANCH}"
          container-env-var-updates: "
          container=zoroaster-service-xdai,name=STAGE,value=STAGING,
          container=zoroaster-service-xdai,name=DB_HOST,value=${DB_HOST},
          container=zoroaster-service-xdai,name=DB_NAME,value=${DB_NAME},
          container=zoroaster-service-xdai,name=DB_USR,value=${DB_USR},
          container=zoroaster-service-xdai,name=DB_PWD,value=${DB_PWD},
          container=zoroaster-service-xdai,name=ETH_NODE,value=${ETH_NODE_XDAI},
          container=zoroaster-service-xdai,name=BACKUP_NODE,value=${ETH_NODE_XDAI},
          container=zoroaster-service-xdai,name=RINKEBY_NODE,value=${RINKEBY_NODE},
          container=zoroaster-service-xdai,name=TWITTER_CONSUMER_KEY,value=${TWITTER_CONSUMER_KEY},
          container=zoroaster-service-xdai,name=TWITTER_CONSUMER_SECRET,value=${TWITTER_CONSUMER_SECRET},
          container=zoroaster-service-xdai,name=NETWORK,value=3_xdai_mainnet,
          container=zoroaster-service-xdai,name=BLOCKS_DELAY,value=${BLOCKS_DELAY_XDAI},
          container=zoroaster-service-xdai,name=POLLING_INTERVAL,value=${POLLING_INTERVAL_XDAI},
          container=zoroaster-service-xdai,name=BLOCKS_INTERVAL,value=${BLOCKS_INTERVAL_XDAI},
          container=zoroaster-service-xdai,name=ETHERSCAN_KEY,value=${ETHERSCAN_KEY}"
          filters:
            branches:
              only: staging
          requires:
            - build-and-push
      - aws-ecs/deploy-service-update:
          family: "zoroaster-prod-service"
          cluster-name: "halxyz-prod-cluster"
          container-image-name-updates: "container=zoroaster-prod-service,tag=${CIRCLE_BRANCH}"
          container-env-var-updates: "
          container=zoroaster-prod-service,name=STAGE,value=PROD,
          container=zoroaster-prod-service,name=DB_HOST,value=${DB_HOST},
          container=zoroaster-prod-service,name=DB_NAME,value=${DB_NAME_PROD},
          container=zoroaster-prod-service,name=DB_USR,value=${DB_USR},
          container=zoroaster-prod-service,name=DB_PWD,value=${DB_PWD},
          container=zoroaster-prod-service,name=ETH_NODE,value=${ETH_NODE_PROD},
          container=zoroaster-prod-service,name=BACKUP_NODE,value=${BACKUP_NODE},
          container=zoroaster-prod-service,name=RINKEBY_NODE,value=${RINKEBY_NODE},
          container=zoroaster-prod-service,name=TWITTER_CONSUMER_KEY,value=${TWITTER_CONSUMER_KEY},
          container=zoroaster-prod-service,name=TWITTER_CONSUMER_SECRET,value=${TWITTER_CONSUMER_SECRET},
          container=zoroaster-prod-service,name=NETWORK,value=1_eth_mainnet,
          container=zoroaster-prod-service,name=BLOCKS_DELAY,value=${BLOCKS_DELAY_ETH_MAINNET},
          container=zoroaster-prod-service,name=POLLING_INTERVAL,value=${POLLING_INTERVAL_ETH_MAINNET},
          container=zoroaster-prod-service,name=BLOCKS_INTERVAL,value=${BLOCKS_INTERVAL_ETH_MAINNET},
          container=zoroaster-prod-service,name=ETHERSCAN_KEY,value=${ETHERSCAN_KEY}"
          filters:
            branches:
              only: master
          requires:
            - build-and-push
      - aws-ecs/deploy-service-update:
          family: "zoroaster-prod-service-xdai"
          cluster-name: "halxyz-prod-cluster"
          container-image-name-updates: "container=zoroaster-prod-service-xdai,tag=${CIRCLE_BRANCH}"
          container-env-var-updates: "
          container=zoroaster-prod-service-xdai,name=STAGE,value=PROD,
          container=zoroaster-prod-service-xdai,name=DB_HOST,value=${DB_HOST},
          container=zoroaster-prod-service-xdai,name=DB_NAME,value=${DB_NAME_PROD},
          container=zoroaster-prod-service-xdai,name=DB_USR,value=${DB_USR},
          container=zoroaster-prod-service-xdai,name=DB_PWD,value=${DB_PWD},
          container=zoroaster-prod-service-xdai,name=ETH_NODE,value=${ETH_NODE_XDAI},
          container=zoroaster-prod-service-xdai,name=BACKUP_NODE,value=${ETH_NODE_XDAI},
          container=zoroaster-prod-service-xdai,name=RINKEBY_NODE,value=${RINKEBY_NODE},
          container=zoroaster-prod-service-xdai,name=TWITTER_CONSUMER_KEY,value=${TWITTER_CONSUMER_KEY},
          container=zoroaster-prod-service-xdai,name=TWITTER_CONSUMER_SECRET,value=${TWITTER_CONSUMER_SECRET},
          container=zoroaster-prod-service-xdai,name=NETWORK,value=3_xdai_mainnet,
          container=zoroaster-prod-service-xdai,name=BLOCKS_DELAY,value=${BLOCKS_DELAY_XDAI},
          container=zoroaster-prod-service-xdai,name=POLLING_INTERVAL,value=${POLLING_INTERVAL_XDAI},
          container=zoroaster-prod-service-xdai,name=BLOCKS_INTERVAL,value=${BLOCKS_INTERVAL_XDAI},
          container=zoroaster-prod-service-xdai,name=ETHERSCAN_KEY,value=${ETHERSCAN_KEY}"
          filters:
            branches:
              only: master
          requires:
            - build-and-push
      - aws-ecs/deploy-service-update:
          family: "zoroaster-prod-service-polygon"
          cluster-name: "halxyz-prod-cluster"
          container-image-name-updates: "container=zoroaster-prod-service-polygon,tag=${CIRCLE_BRANCH}"
          container-env-var-updates: "
          container=zoroaster-prod-service-polygon,name=STAGE,value=PROD,
          container=zoroaster-prod-service-polygon,name=DB_HOST,value=${DB_HOST},
          container=zoroaster-prod-service-polygon,name=DB_NAME,value=${DB_NAME_PROD},
          container=zoroaster-prod-service-polygon,name=DB_USR,value=${DB_USR},
          container=zoroaster-prod-service-polygon,name=DB_PWD,value=${DB_PWD},
          container=zoroaster-prod-service-polygon,name=ETH_NODE,value=${ETH_NODE_POLYGON},
          container=zoroaster-prod-service-polygon,name=BACKUP_NODE,value=${ETH_NODE_POLYGON},
          container=zoroaster-prod-service-polygon,name=RINKEBY_NODE,value=${RINKEBY_NODE},
          container=zoroaster-prod-service-polygon,name=TWITTER_CONSUMER_KEY,value=${TWITTER_CONSUMER_KEY},
          container=zoroaster-prod-service-polygon,name=TWITTER_CONSUMER_SECRET,value=${TWITTER_CONSUMER_SECRET},
          container=zoroaster-prod-service-polygon,name=NETWORK,value=5_polygon_mainnet,
          container=zoroaster-prod-service-polygon,name=BLOCKS_DELAY,value=${BLOCKS_DELAY_POLYGON},
          container=zoroaster-prod-service-polygon,name=POLLING_INTERVAL,value=${POLLING_INTERVAL_POLYGON},
          container=zoroaster-prod-service-polygon,name=BLOCKS_INTERVAL,value=${BLOCKS_INTERVAL_POLYGON},
          container=zoroaster-prod-service-polygon,name=ETHERSCAN_KEY,value=${ETHERSCAN_KEY}"
          filters:
            branches:
              only: master
          requires:
            - build-and-push
